name: Update deaths-and-casualties source data

permissions:
  contents: write
  id-token: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  update-data:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout self
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: true

      - name: Checkout war-fire-model
        uses: actions/checkout@v4
        with:
          repository: TheEconomist/the-economist-war-fire-model
          path: war-fire-model
          token: ${{ secrets.PAT_TOKEN }}
          fetch-depth: 1   # only latest commit
          sparse-checkout: |
            output-data/strikes_by_location_and_day.csv
          sparse-checkout-cone-mode: true

      # … rest of your steps …

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Update deaths-and-casualties data & run meta-estimate.R'
          add: |
            source-data/deaths-and-casualties-data/*.csv
            output-data/**
